Sort addon category list alphabetically by name
SingularityMods/singularity-core pull request #9
Opened 2020-11-21 21:58 UTC by kfr2

The items fed into the Category dropdown will now be sorted
alphabetically by their `name` attribute. As an example, this list
may now look like:
* All
* Achievements
* Action Bars
* Alchemy
* ...

rather than:
* All
* Chat & Communication
* Auction & Economy
* Audio & Video
* PvP
* ...

![sorted-categories](https://user-images.githubusercontent.com/410310/99888426-b7d69f80-2c1a-11eb-8c2f-f0eb1175de34.PNG)

Implements #8

2020-11-22 17:20 UTC, sbsrnt requested changes

2020-11-22 17:20 UTC, sbsrnt commented on src/main-process/Game/get-game-data-sync.js
> +    let categories = storageService.getGameData(gameId.toString()).categories;
`const` instead of `let`

2020-11-22 20:11 UTC, kfr2 commented on src/main-process/Game/get-game-data-sync.js
> +    let categories = storageService.getGameData(gameId.toString()).categories;
Thanks! I have made this change.

2020-11-23 21:08 UTC, mlalibs commented
Looks good to me.

2020-11-23 21:08 UTC, merged